#서버설정
sever:
 port: 9090
 servlet:
    encoding:
      charset: UTF-8

#jsp설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      sufffx: .jsp
#  config:
#    improt:



  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring